// Sirobo Code Generators
// Generate Arduino C++ code and Live commands from Blockly blocks

import Blockly from 'blockly'

// =====================================================
// ARDUINO CODE GENERATOR
// =====================================================

export const arduinoGenerator = new Blockly.Generator('Arduino')

arduinoGenerator.init = function(workspace) {
  this.definitions_ = Object.create(null)
  this.includes_ = Object.create(null)
  this.setupCode_ = []
  this.variableDB_ = new Blockly.Names(Blockly.Names.DEVELOPER_VARIABLE_TYPE)
}

arduinoGenerator.finish = function(code) {
  // Includes
  const includes = Object.values(this.includes_).join('\n')
  
  // Definitions
  const definitions = Object.values(this.definitions_).join('\n')
  
  // Setup code
  const setup = this.setupCode_.join('\n')
  
  return `// Sirobo - Generated Code
// Auto-generated by Sirobo Blockly Editor

${includes}

${definitions}

void setup() {
  Serial.begin(115200);
  siroboInit();
${setup}
}

void loop() {
${code}
}
`
}

arduinoGenerator.scrub_ = function(block, code) {
  const nextBlock = block.nextConnection && block.nextConnection.targetBlock()
  const nextCode = arduinoGenerator.blockToCode(nextBlock)
  return code + nextCode
}

// Order of operations
arduinoGenerator.ORDER_ATOMIC = 0
arduinoGenerator.ORDER_UNARY_POSTFIX = 1
arduinoGenerator.ORDER_UNARY_PREFIX = 2
arduinoGenerator.ORDER_MULTIPLICATIVE = 3
arduinoGenerator.ORDER_ADDITIVE = 4
arduinoGenerator.ORDER_RELATIONAL = 5
arduinoGenerator.ORDER_EQUALITY = 6
arduinoGenerator.ORDER_LOGICAL_AND = 7
arduinoGenerator.ORDER_LOGICAL_OR = 8
arduinoGenerator.ORDER_CONDITIONAL = 9
arduinoGenerator.ORDER_ASSIGNMENT = 10
arduinoGenerator.ORDER_NONE = 99

// Motor blocks
arduinoGenerator['robot_maju'] = function(block) {
  const speed = arduinoGenerator.valueToCode(block, 'SPEED', arduinoGenerator.ORDER_ATOMIC) || '50'
  return `robotForward(${speed});\n`
}

arduinoGenerator['robot_mundur'] = function(block) {
  const speed = arduinoGenerator.valueToCode(block, 'SPEED', arduinoGenerator.ORDER_ATOMIC) || '50'
  return `robotBackward(${speed});\n`
}

arduinoGenerator['robot_belok_kiri'] = function(block) {
  const speed = arduinoGenerator.valueToCode(block, 'SPEED', arduinoGenerator.ORDER_ATOMIC) || '50'
  return `robotTurnLeft(${speed});\n`
}

arduinoGenerator['robot_belok_kanan'] = function(block) {
  const speed = arduinoGenerator.valueToCode(block, 'SPEED', arduinoGenerator.ORDER_ATOMIC) || '50'
  return `robotTurnRight(${speed});\n`
}

arduinoGenerator['robot_putar'] = function(block) {
  const angle = arduinoGenerator.valueToCode(block, 'ANGLE', arduinoGenerator.ORDER_ATOMIC) || '90'
  return `robotRotate(${angle});\n`
}

arduinoGenerator['robot_putar_sudut'] = function(block) {
  const angle = block.getFieldValue('ANGLE')
  return `robotRotate(${angle});\n`
}

arduinoGenerator['robot_stop'] = function(block) {
  return `robotStop();\n`
}

arduinoGenerator['robot_atur_motor'] = function(block) {
  const left = arduinoGenerator.valueToCode(block, 'LEFT', arduinoGenerator.ORDER_ATOMIC) || '0'
  const right = arduinoGenerator.valueToCode(block, 'RIGHT', arduinoGenerator.ORDER_ATOMIC) || '0'
  return `setMotors(${left}, ${right});\n`
}

// Sensor blocks
arduinoGenerator['sensor_garis'] = function(block) {
  const index = block.getFieldValue('INDEX')
  return [`getLineSensor(${index})`, arduinoGenerator.ORDER_ATOMIC]
}

arduinoGenerator['sensor_garis_deteksi'] = function(block) {
  const index = block.getFieldValue('INDEX')
  return [`isLineDetected(${index})`, arduinoGenerator.ORDER_ATOMIC]
}

arduinoGenerator['sensor_jarak'] = function(block) {
  return [`getDistance()`, arduinoGenerator.ORDER_ATOMIC]
}

arduinoGenerator['sensor_jarak_kondisi'] = function(block) {
  const distance = arduinoGenerator.valueToCode(block, 'DISTANCE', arduinoGenerator.ORDER_ATOMIC) || '20'
  return [`(getDistance() < ${distance})`, arduinoGenerator.ORDER_RELATIONAL]
}

arduinoGenerator['sensor_ldr'] = function(block) {
  const index = block.getFieldValue('INDEX')
  return [`getLDR(${index})`, arduinoGenerator.ORDER_ATOMIC]
}

arduinoGenerator['sensor_imu_yaw'] = function(block) {
  return [`getYaw()`, arduinoGenerator.ORDER_ATOMIC]
}

arduinoGenerator['sensor_imu_pitch'] = function(block) {
  return [`getPitch()`, arduinoGenerator.ORDER_ATOMIC]
}

arduinoGenerator['sensor_imu_roll'] = function(block) {
  return [`getRoll()`, arduinoGenerator.ORDER_ATOMIC]
}

arduinoGenerator['sensor_imu_reset'] = function(block) {
  return `resetYaw();\n`
}

arduinoGenerator['sensor_button'] = function(block) {
  const index = block.getFieldValue('INDEX')
  return [`isButtonPressed(${index})`, arduinoGenerator.ORDER_ATOMIC]
}

// LED blocks
arduinoGenerator['led_nyala'] = function(block) {
  const index = block.getFieldValue('INDEX')
  const color = block.getFieldValue('COLOR')
  
  if (color === 'rainbow') {
    return `setLEDRainbow(${index === 'all' ? -1 : index});\n`
  }
  
  const colorMap = {
    red: '255, 0, 0',
    green: '0, 255, 0',
    blue: '0, 0, 255',
    yellow: '255, 255, 0',
    purple: '128, 0, 128',
    orange: '255, 165, 0',
    white: '255, 255, 255',
  }
  
  if (index === 'all') {
    return `setAllLEDs(${colorMap[color]});\n`
  }
  return `setLED(${index}, ${colorMap[color]});\n`
}

arduinoGenerator['led_rgb'] = function(block) {
  const index = block.getFieldValue('INDEX')
  const r = arduinoGenerator.valueToCode(block, 'R', arduinoGenerator.ORDER_ATOMIC) || '0'
  const g = arduinoGenerator.valueToCode(block, 'G', arduinoGenerator.ORDER_ATOMIC) || '0'
  const b = arduinoGenerator.valueToCode(block, 'B', arduinoGenerator.ORDER_ATOMIC) || '0'
  
  if (index === 'all') {
    return `setAllLEDs(${r}, ${g}, ${b});\n`
  }
  return `setLED(${index}, ${r}, ${g}, ${b});\n`
}

arduinoGenerator['led_mati'] = function(block) {
  const index = block.getFieldValue('INDEX')
  if (index === 'all') {
    return `setAllLEDs(0, 0, 0);\n`
  }
  return `setLED(${index}, 0, 0, 0);\n`
}

arduinoGenerator['led_kedip'] = function(block) {
  const times = arduinoGenerator.valueToCode(block, 'TIMES', arduinoGenerator.ORDER_ATOMIC) || '3'
  return `blinkLEDs(${times});\n`
}

// Sound blocks
arduinoGenerator['bunyi_nada'] = function(block) {
  const note = block.getFieldValue('NOTE')
  const duration = arduinoGenerator.valueToCode(block, 'DURATION', arduinoGenerator.ORDER_ATOMIC) || '200'
  return `playTone(${note}, ${duration});\n`
}

arduinoGenerator['bunyi_frekuensi'] = function(block) {
  const freq = arduinoGenerator.valueToCode(block, 'FREQ', arduinoGenerator.ORDER_ATOMIC) || '440'
  const duration = arduinoGenerator.valueToCode(block, 'DURATION', arduinoGenerator.ORDER_ATOMIC) || '200'
  return `playTone(${freq}, ${duration});\n`
}

arduinoGenerator['bunyi_melody'] = function(block) {
  const melody = block.getFieldValue('MELODY')
  return `playMelody("${melody}");\n`
}

arduinoGenerator['bunyi_stop'] = function(block) {
  return `stopTone();\n`
}

// Display blocks
arduinoGenerator['oled_tampilkan_teks'] = function(block) {
  const text = arduinoGenerator.valueToCode(block, 'TEXT', arduinoGenerator.ORDER_ATOMIC) || '""'
  const line = block.getFieldValue('LINE')
  return `displayText(${line}, ${text});\n`
}

arduinoGenerator['oled_tampilkan_angka'] = function(block) {
  const number = arduinoGenerator.valueToCode(block, 'NUMBER', arduinoGenerator.ORDER_ATOMIC) || '0'
  const line = block.getFieldValue('LINE')
  return `displayNumber(${line}, ${number});\n`
}

arduinoGenerator['oled_hapus'] = function(block) {
  return `clearDisplay();\n`
}

arduinoGenerator['oled_gambar'] = function(block) {
  const image = block.getFieldValue('IMAGE')
  return `displayImage("${image}");\n`
}

// Line follower blocks
arduinoGenerator['line_follower_mulai'] = function(block) {
  const speed = arduinoGenerator.valueToCode(block, 'SPEED', arduinoGenerator.ORDER_ATOMIC) || '50'
  return `startLineFollower(${speed});\n`
}

arduinoGenerator['line_follower_stop'] = function(block) {
  return `stopLineFollower();\n`
}

arduinoGenerator['line_follower_sampai_persimpangan'] = function(block) {
  const type = block.getFieldValue('TYPE')
  return [`detectIntersection("${type}")`, arduinoGenerator.ORDER_ATOMIC]
}

// Timing blocks
arduinoGenerator['tunggu'] = function(block) {
  const time = arduinoGenerator.valueToCode(block, 'TIME', arduinoGenerator.ORDER_ATOMIC) || '1'
  const unit = block.getFieldValue('UNIT')
  
  if (unit === 'seconds') {
    return `delay(${time} * 1000);\n`
  }
  return `delay(${time});\n`
}

arduinoGenerator['waktu_berjalan'] = function(block) {
  return [`millis()`, arduinoGenerator.ORDER_ATOMIC]
}

// Calibration blocks
arduinoGenerator['kalibrasi_motor'] = function(block) {
  const left = arduinoGenerator.valueToCode(block, 'LEFT', arduinoGenerator.ORDER_ATOMIC) || '0'
  const right = arduinoGenerator.valueToCode(block, 'RIGHT', arduinoGenerator.ORDER_ATOMIC) || '0'
  return `setMotorCalibration(${left}, ${right});\n`
}

arduinoGenerator['simpan_kalibrasi'] = function(block) {
  return `saveCalibration();\n`
}

arduinoGenerator['auto_kalibrasi'] = function(block) {
  return `autoCalibrateStraight();\n`
}

// Event blocks
arduinoGenerator['saat_mulai'] = function(block) {
  const code = arduinoGenerator.statementToCode(block, 'DO')
  this.setupCode_.push(code)
  return ''
}

arduinoGenerator['selalu_ulangi'] = function(block) {
  const code = arduinoGenerator.statementToCode(block, 'DO')
  return code
}

// Standard blocks
arduinoGenerator['math_number'] = function(block) {
  const code = Number(block.getFieldValue('NUM'))
  return [code, arduinoGenerator.ORDER_ATOMIC]
}

arduinoGenerator['text'] = function(block) {
  const text = block.getFieldValue('TEXT')
  return [`"${text}"`, arduinoGenerator.ORDER_ATOMIC]
}

arduinoGenerator['logic_boolean'] = function(block) {
  const code = block.getFieldValue('BOOL') === 'TRUE' ? 'true' : 'false'
  return [code, arduinoGenerator.ORDER_ATOMIC]
}

arduinoGenerator['controls_if'] = function(block) {
  let code = ''
  let n = 0
  
  do {
    const conditionCode = arduinoGenerator.valueToCode(block, 'IF' + n, arduinoGenerator.ORDER_NONE) || 'false'
    const branchCode = arduinoGenerator.statementToCode(block, 'DO' + n)
    
    code += (n === 0 ? 'if' : ' else if') + ` (${conditionCode}) {\n${branchCode}}`
    n++
  } while (block.getInput('IF' + n))
  
  if (block.getInput('ELSE')) {
    const branchCode = arduinoGenerator.statementToCode(block, 'ELSE')
    code += ` else {\n${branchCode}}`
  }
  
  return code + '\n'
}

arduinoGenerator['controls_repeat_ext'] = function(block) {
  const times = arduinoGenerator.valueToCode(block, 'TIMES', arduinoGenerator.ORDER_ATOMIC) || '0'
  const branch = arduinoGenerator.statementToCode(block, 'DO')
  return `for (int i = 0; i < ${times}; i++) {\n${branch}}\n`
}

arduinoGenerator['controls_whileUntil'] = function(block) {
  const until = block.getFieldValue('MODE') === 'UNTIL'
  const condition = arduinoGenerator.valueToCode(block, 'BOOL', arduinoGenerator.ORDER_NONE) || 'false'
  const branch = arduinoGenerator.statementToCode(block, 'DO')
  return `while (${until ? '!' : ''}(${condition})) {\n${branch}}\n`
}

arduinoGenerator['logic_compare'] = function(block) {
  const operator = {
    'EQ': '==',
    'NEQ': '!=',
    'LT': '<',
    'LTE': '<=',
    'GT': '>',
    'GTE': '>='
  }[block.getFieldValue('OP')]
  const a = arduinoGenerator.valueToCode(block, 'A', arduinoGenerator.ORDER_RELATIONAL) || '0'
  const b = arduinoGenerator.valueToCode(block, 'B', arduinoGenerator.ORDER_RELATIONAL) || '0'
  return [`${a} ${operator} ${b}`, arduinoGenerator.ORDER_RELATIONAL]
}

arduinoGenerator['logic_operation'] = function(block) {
  const operator = block.getFieldValue('OP') === 'AND' ? '&&' : '||'
  const order = block.getFieldValue('OP') === 'AND' 
    ? arduinoGenerator.ORDER_LOGICAL_AND 
    : arduinoGenerator.ORDER_LOGICAL_OR
  const a = arduinoGenerator.valueToCode(block, 'A', order) || 'false'
  const b = arduinoGenerator.valueToCode(block, 'B', order) || 'false'
  return [`${a} ${operator} ${b}`, order]
}

arduinoGenerator['logic_negate'] = function(block) {
  const a = arduinoGenerator.valueToCode(block, 'BOOL', arduinoGenerator.ORDER_UNARY_PREFIX) || 'true'
  return [`!${a}`, arduinoGenerator.ORDER_UNARY_PREFIX]
}

arduinoGenerator['math_arithmetic'] = function(block) {
  const operator = {
    'ADD': '+',
    'MINUS': '-',
    'MULTIPLY': '*',
    'DIVIDE': '/',
    'POWER': '**'
  }[block.getFieldValue('OP')]
  const order = operator === '+' || operator === '-' 
    ? arduinoGenerator.ORDER_ADDITIVE 
    : arduinoGenerator.ORDER_MULTIPLICATIVE
  const a = arduinoGenerator.valueToCode(block, 'A', order) || '0'
  const b = arduinoGenerator.valueToCode(block, 'B', order) || '0'
  
  if (operator === '**') {
    return [`pow(${a}, ${b})`, arduinoGenerator.ORDER_ATOMIC]
  }
  return [`${a} ${operator} ${b}`, order]
}

arduinoGenerator['math_random_int'] = function(block) {
  const from = arduinoGenerator.valueToCode(block, 'FROM', arduinoGenerator.ORDER_ATOMIC) || '0'
  const to = arduinoGenerator.valueToCode(block, 'TO', arduinoGenerator.ORDER_ATOMIC) || '100'
  return [`random(${from}, ${to} + 1)`, arduinoGenerator.ORDER_ATOMIC]
}

// =====================================================
// LIVE COMMAND GENERATOR
// =====================================================

export const liveGenerator = new Blockly.Generator('Live')

liveGenerator.ORDER_ATOMIC = 0
liveGenerator.ORDER_NONE = 99

// Generate JSON commands for live execution
liveGenerator['robot_maju'] = function(block) {
  const speed = liveGenerator.valueToCode(block, 'SPEED', liveGenerator.ORDER_ATOMIC) || '50'
  return JSON.stringify({ type: 'forward', speed: parseInt(speed) }) + '\n'
}

liveGenerator['robot_mundur'] = function(block) {
  const speed = liveGenerator.valueToCode(block, 'SPEED', liveGenerator.ORDER_ATOMIC) || '50'
  return JSON.stringify({ type: 'backward', speed: parseInt(speed) }) + '\n'
}

liveGenerator['robot_stop'] = function(block) {
  return JSON.stringify({ type: 'stop' }) + '\n'
}

liveGenerator['led_nyala'] = function(block) {
  const index = block.getFieldValue('INDEX')
  const color = block.getFieldValue('COLOR')
  return JSON.stringify({ type: 'led', index, color }) + '\n'
}

liveGenerator['tunggu'] = function(block) {
  const time = liveGenerator.valueToCode(block, 'TIME', liveGenerator.ORDER_ATOMIC) || '1'
  const unit = block.getFieldValue('UNIT')
  const ms = unit === 'seconds' ? parseInt(time) * 1000 : parseInt(time)
  return JSON.stringify({ type: 'delay', ms }) + '\n'
}

liveGenerator['math_number'] = function(block) {
  return [block.getFieldValue('NUM'), liveGenerator.ORDER_ATOMIC]
}

liveGenerator.scrub_ = function(block, code) {
  const nextBlock = block.nextConnection && block.nextConnection.targetBlock()
  const nextCode = liveGenerator.blockToCode(nextBlock)
  return code + nextCode
}

export default { arduinoGenerator, liveGenerator }
